# Generated by Django 3.1.1 on 2020-09-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttribType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True)),
                ('raw_type', models.IntegerField(choices=[(0, 'BOOL'), (1, 'FLOAT'), (2, 'INTEGER'), (3, 'STRING'), (4, 'DICT')])),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('attribute_json', models.JSONField(blank=True, default=dict)),
                ('next_vertex_id', models.IntegerField(default=1)),
                ('next_transaction_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GraphAttribDefTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('descr', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('default_str', models.TextField(blank=True, default=None, null=True)),
                ('graph_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.graph')),
                ('type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attribtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraphAttribDefVertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('descr', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('default_str', models.TextField(blank=True, default=None, null=True)),
                ('graph_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.graph')),
                ('type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attribtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.IntegerField()),
                ('tx_dir', models.BooleanField(default=True)),
                ('attribute_json', models.JSONField(blank=True, default=dict)),
                ('graph_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.graph')),
            ],
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vx_id', models.IntegerField()),
                ('attribute_json', models.JSONField(blank=True, default=dict)),
                ('graph_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.graph')),
            ],
        ),
        migrations.CreateModel(
            name='VertexAttrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.TextField(blank=True, default='')),
                ('attrib_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.graphattribdefvertex')),
                ('vertex_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertex_attribs', to='app.vertex')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAttrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.TextField(blank=True, default='')),
                ('attrib_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.graphattribdeftrans')),
                ('transaction_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='vx_dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='app.vertex'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vx_src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='app.vertex'),
        ),
        migrations.CreateModel(
            name='SchemaAttribDefVertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('descr', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('default_str', models.TextField(blank=True, default=None, null=True)),
                ('schema_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.schema')),
                ('type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attribtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaAttribDefTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('descr', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('default_str', models.TextField(blank=True, default=None, null=True)),
                ('schema_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.schema')),
                ('type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attribtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaAttribDefGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('descr', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('default_str', models.TextField(blank=True, default=None, null=True)),
                ('schema_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.schema')),
                ('type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attribtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraphAttribDefGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('descr', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('default_str', models.TextField(blank=True, default=None, null=True)),
                ('graph_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.graph')),
                ('type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attribtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraphAttrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.TextField(blank=True, default='')),
                ('attrib_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.graphattribdefgraph')),
                ('graph_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_attribs', to='app.graph')),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='schema_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.schema'),
        ),
        migrations.AddConstraint(
            model_name='vertexattrib',
            constraint=models.UniqueConstraint(fields=('vertex_fk', 'attrib_fk'), name='unique attrib per vertex'),
        ),
        migrations.AddConstraint(
            model_name='graphattrib',
            constraint=models.UniqueConstraint(fields=('graph_fk', 'attrib_fk'), name='unique attrib per graph'),
        ),
    ]
