version: '3'

services: 
  db:
    # Define the Database service
    # Database name, user, and password must also be set in DATABASES block of the settings.py file.
    image: mariadb
    restart: always
    command: ['--max_allowed_packet=256M', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    env_file: &envfile
      - env.env
    container_name: maria_db
    environment:
      MYSQL_DATABASE: "docker-db"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "dockerpassword"
      MYSQL_ROOT_PASSWORD: "dockerrootpassword"

  redis:
    # Define the channels layer storage mechanism. USed to hold data to be sent out on sockets via channels
    image: redis:alpine
    ports:
      - 6379:6379

  backend:
    # Define the backend web application, This will be accessed at 
    # http://127.0.0.1:8000/
    build: .
    image: &web web
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata attribtype.json && python -u manage.py runserver 0.0.0.0:8000"
    env_file: *envfile
    container_name: constellation_backend
    restart: always
    volumes:
      - .:/app
    ports: 
      - "8000:8000"
    depends_on:
      - db
      - redis
    links:
      - redis

